# the compiler: gcc for C program, define as g++ for C++
CC = g++
# compiler flags:
CFLAGS  = -g -Wall -std=c++11


main: main.o rand-normal.o doubleTypeArray.o 
	$(CC) $(CFLAGS) -o main main.o rand-normal.o doubleTypeArray.o 
main.o: 

rand-normal.o:

doubleTypeArray.o:
